name: Update Upstream

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' #设置定时任务
jobs:
  rebase-upstream-main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Update Upstream Main Branch
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git remote add upstream https://github.com/ddgksf2013/Rewrite.git
        git remote -v
        git fetch upstream
        git checkout master || git checkout -b master origin/main
        git rebase --strategy-option=ours upstream/master
        git push -f origin master
        git checkout dev || git checkout -b dev origin/dev
        git rebase master
        git push -f origin dev
